"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?
"""


def genPen(n):
    return n * (3 * n - 1) / 2


def isPen(n):
    return ((((24 * n + 1) ** 0.5) + 1) / 6) % 1 == 0


lst = []
for i in range(1,5000):
    lst.append(genPen(i))
    # print(lst[len(lst) - 1])

minimum = genPen(50001)
for i in range(len(lst)):
    for j in range(i-1):
        if isPen(lst[i] + lst[j]) and isPen(abs(lst[i] - lst[j])):
            minimum = min(minimum, lst[i] - lst[j])
            print(minimum)
